platform:
  - x86

environment:
  CYG_ROOT: "C:\\cygwin"
  CYG_BASH: "%CYG_ROOT%\\bin\\bash -lc"
  TESTS: "false"
  OPAM_SWITCH: "4.03.0+mingw64c"
  PINS: "hvsock:https://github.com/mirage/ocaml-hvsock.git#v0.11.1"

install:
  - appveyor DownloadFile https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/appveyor-opam.sh
  - "%CYG_ROOT%\\setup-x86.exe -qnNdO -R %CYG_ROOT% -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P rsync -P patch -P diffutils.3.5-1 -P make -P git -P perl -P mingw64-x86_64-gcc-core"

build_script:
  - "%CYG_BASH% '${APPVEYOR_BUILD_FOLDER}/appveyor-opam.sh'"
  - "%CYG_BASH% -c 'cd ${APPVEYOR_BUILD_FOLDER}; make exe COMMIT'"
  - cmd: copy %APPVEYOR_BUILD_FOLDER%\Datakit\datakit.exe c:\projects\datakit\com.docker.db.exe
  - cmd: copy %APPVEYOR_BUILD_FOLDER%\Datakit\zlib1.dll c:\projects\datakit\zlib1.dll

artifacts:
  - path: "com.docker.db.exe"
  - path: "zlib1.dll"
  - path: "COMMIT"
